set wshshell = wscript.CreateObject("wScript.Shell")
 wshshell.run "Notepad"
 wscript.sleep 400
 wshshell.sendkeys "R"
 wscript.sleep 100
 wshshell.sendkeys "A"
 wscript.sleep 120
 wshshell.sendkeys "I"
 wscript.sleep 200
 wshshell.sendkeys "N"
 wscript.sleep 100
 wshshell.sendkeys "B"
 wscript.sleep 140
 wshshell.sendkeys "O"
 wscript.sleep 100
 wshshell.sendkeys "W"
 wscript.sleep 50
 wshshell.sendkeys "F"
 wscript.sleep 120
 wshshell.sendkeys "L"
 wscript.sleep 170
 wshshell.sendkeys "O"
 wscript.sleep 100
 wshshell.sendkeys "O"
 wscript.sleep 120
 wshshell.sendkeys "D"
 wscript.sleep 160
 wshshell.sendkeys "1"
 wscript.sleep 200
wscript.sleep 100